name: CI

on:
  # push:
  #   branches: 
  #       - "master"
  schedule:
    - cron: '15 13 * * *'
  workflow_dispatch:

env:
  GIT_SECRET_MAIN: ${{ secrets.GIT_SECRET_MAIN }}
  DEBIAN_FRONTEND: noninteractive

jobs:
  build:

    defaults:
      run:
        shell: bash

    timeout-minutes: 360
    
    strategy:

      fail-fast: false

    name: runner
    
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/setup-python@v4
        name: Setup python
        id: python
        with:
          python-version: "3.8"

      - name: Checkout
        run: |
          git clone https://${GIT_SECRET_MAIN}@github.com/Clurfe/prox-gen.git

      - name: prep
        run: |
          cd prox-gen
          chmod +x prep.sh
          ./prep.sh

      - name: get-proxy
        run: |
          cd prox-gen
          chmod +x get-proxy.sh
          ./get-proxy.sh

      - name: clean proxy
        run: |
          cd prox-gen
          pip install requests fake_headers
          python3 proxy_check-1.py
          python3 proxy_check-2.py
          python3 proxy_check-3.py
          cat "result-checked-1.txt" > result-checked.txt
          cat "result-checked-2.txt" >> result-checked.txt
          cat "result-checked-3.txt" >> result-checked.txt

      - name: push changes
        run: |
          cd prox-gen
          echo "$(date +"%Y%m%d")" >> last-changes.txt
          git config user.name "Clurfe"
          git config user.email "zycromerz@gmail.com"
          git add last-changes.txt result.txt result-checked.txt
          git commit -sm "update $(date +"%Y%m%d")"
          git show
          git push --all origin -f